version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      astro:
        patterns: ["astro", "@astrojs*"]
      d2:
        patterns: ["astro-d2", "@terrastruct/d2"]
      icons:
        patterns: ["unplugin-icons", "@iconify*"]
      lunaria:
        patterns: ["@lunariajs*"]
      oxc:
        patterns: ["oxfmt", "oxlint*"]
      react:
        patterns: ["react", "react-dom", "@types/react", "@types/react-dom"]
      tailwindcss:
        patterns: ["tailwindcss", "@tailwindcss*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
