name: Astro

on:
  pull_request:
  push:
    branches:
      - main
      - next
permissions:
  contents: read
env:
  ASTRO_TELEMETRY_DISABLED: true
  ASTRO_DISABLE_UPDATE_CHECK: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set Up Deno
        uses: denoland/setup-deno@ff4860f9d7236f320afa0f82b7e6457384805d05 # v2.0.4

      - name: Cache Build
        id: cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/deno
            ${{ github.workspace }}/node_modules/.astro
          key: astro-build-${{ hashFiles('**/deno.lock') }}-${{ hashFiles('**/astro.config.mjs', '**/*.jpg', '**/*.mdx', '**/*.png', '**/*.svg', '**/*.webp') }}
          restore-keys: |
            astro-build-${{ hashFiles('**/deno.lock') }}-

      - name: Install Dependencies
        run: deno ci

      - name: Build With Astro
        run: deno run build

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set Up Deno
        uses: denoland/setup-deno@ff4860f9d7236f320afa0f82b7e6457384805d05 # v2.0.4

      - name: Cache Build
        id: cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/deno
            ${{ github.workspace }}/node_modules/.astro
          key: astro-build-${{ hashFiles('**/deno.lock') }}-${{ hashFiles('**/astro.config.mjs', '**/*.jpg', '**/*.mdx', '**/*.png', '**/*.svg', '**/*.webp') }}
          restore-keys: |
            astro-build-${{ hashFiles('**/deno.lock') }}-

      - name: Install Dependencies
        run: deno ci

      - name: Run Checks With Astro
        run: deno run check

  check-links:
    name: Check Links
    runs-on: ubuntu-latest
    env:
      CHECK_LINKS: true
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set Up Deno
        uses: denoland/setup-deno@ff4860f9d7236f320afa0f82b7e6457384805d05 # v2.0.4

      # We don't want to save caches from these runs because they can invalidate it. See: https://starlight-links-validator.vercel.app/getting-started/#installation
      - name: Restore Cache
        id: cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/deno
            ${{ github.workspace }}/node_modules/.astro
          key: astro-build-${{ hashFiles('**/deno.lock') }}-${{ hashFiles('**/astro.config.mjs', '**/*.jpg', '**/*.mdx', '**/*.png', '**/*.svg', '**/*.webp') }}
          restore-keys: |
            astro-build-${{ hashFiles('**/deno.lock') }}-

      - name: Install Dependencies
        run: deno ci

      - name: Run Build And Check
        run: deno run build
