name: Check & Lint

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: check-and-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [check, lint, fmt:check]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up PNPM
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true
          runtime: node@lts

      - run: pnpm run ${{ matrix.task }}
