name: Lunaria

on:
  pull_request:
    branches:
      - main
      - next
    paths:
      - "src/content/docs/*/**/*.mdx"
permissions:
  contents: read
env:
  FORCE_COLOR: 1

jobs:
  overview:
    name: Overview
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Necessary for Lunaria to work properly
          fetch-depth: 0

      - name: Set Up PNPM
        uses: pnpm/setup@4700d737c3d7a2e7199f3d42a920f0bf7f34e411 # v2.0.1
        with:
          version: 11
          cache: true
          runtime: node@lts

      - name: Generate Lunaria Overview
        # TODO: Swap to lunariajs/action once it has releases. Note that this action is still from the dev of Lunaria so it's still official.
        uses: yanthomasdev/lunaria-action@06ad5ab2704d030708baf3b279ca0446b418e853 # v0.1.0
