name: Lunaria

on:
  pull_request:
    branches:
      - main
      - next
    paths:
      - "src/content/docs/*/**/*.mdx"
permissions:
  contents: read

jobs:
  overview:
    name: Overview
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          # Necessary for Lunaria to work properly
          fetch-depth: 0

      - name: Set Up Deno
        uses: denoland/setup-deno@ff4860f9d7236f320afa0f82b7e6457384805d05 # v2.0.4
        with:
          cache: true

      - name: Install Dependencies
        run: deno ci

      - name: Generate Lunaria Overview
        # TODO: Swap to lunariajs/action once it has releases. Note that this action is still from the dev of Lunaria so it's still official.
        uses: yanthomasdev/lunaria-action@06ad5ab2704d030708baf3b279ca0446b418e853 # v0.1.0
