name: Oxfmt

on:
  pull_request:
  push:
    branches:
      - main
      - next
permissions:
  contents: read

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set Up Deno
        uses: denoland/setup-deno@ff4860f9d7236f320afa0f82b7e6457384805d05 # v2.0.4
        with:
          cache: true

      - name: Install Dependencies
        run: deno ci

      - name: Run Oxfmt
        uses: oxc-project/oxfmt-action@5f25fc2dccfa7335bc29ceceecc610d8b5c93d64 # v0.0.1
        with:
          config: oxfmt.config.ts
