name: Oxfmt

on:
  pull_request:
  push:
    branches:
      - main
      - next
permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Oxfmt
        uses: oxc-project/oxfmt-action@5f25fc2dccfa7335bc29ceceecc610d8b5c93d64 # v0.0.1
        with:
          config: oxfmt.config.ts
