name: Oxfmt

on:
  pull_request:
  push:
    branches:
      - main
      - next
permissions:
  contents: read

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093

      - name: Cache Build
        id: cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.local/share/pnpm
            ${{ github.workspace }}/node_modules/.astro
          key: astro-build-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/astro.config.mjs', '**/*.jpg', '**/*.mdx', '**/*.png', '**/*.svg', '**/*.webp') }}
          restore-keys: |
            astro-build-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install Dependencies
        run: pnpm ci

      - name: Run Oxfmt
        uses: oxc-project/oxfmt-action@5f25fc2dccfa7335bc29ceceecc610d8b5c93d64 # v0.0.1
        with:
          config: oxfmt.config.ts
