name: Oxlint

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "*.json"
  push:
    branches:
      - main
      - next
    paths-ignore:
      - "*.md"
      - "*.json"
permissions:
  contents: read
  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*

      - name: Set up Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest

      - name: Cache dependencies
        id: cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-oxc-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/oxfmt.config.ts', '**/oxlint.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-oxc-${{ hashFiles('**/bun.lock') }}-

      - name: Install dependencies
        run: bun ci

      - name: Run Oxlint
        uses: oxc-project/oxlint-action@92eec2c4d5dbbb882c926478438aa4b7f20ffe2d # v3.0.0
        with:
          config: oxlint.config.ts
