name: Oxlint

on:
  pull_request:
    paths:
      - "**/*.mjs"
      - "**/*.tsx"
      - "**/*.ts"
  push:
    branches:
      - main
      - next
    paths:
      - "**/*.mjs"
      - "**/*.tsx"
      - "**/*.ts"
permissions:
  contents: read

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set Up Deno
        uses: denoland/setup-deno@ff4860f9d7236f320afa0f82b7e6457384805d05 # v2.0.4
        with:
          cache: true

      - name: Install Dependencies
        run: deno ci

      - name: Run Oxlint
        uses: oxc-project/oxlint-action@b78c21302e4bc637e83927135c35a6684de1053e # v3.1.0
        with:
          config: oxlint.config.ts
          plugins: node react react-perf
